version: 2

defaults: &defaults
  working_directory: ~/auto-presentation
  docker:
    - image: circleci/node:latest-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - auto-presentation-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
            - auto-presentation-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - auto-presentation-{{ .Branch }}
            # Find the most recent cache used from any branch
            - auto-presentation-master
            - auto-presentation-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: auto-presentation-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-presentation
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auto-presentation
      - run:
          name: "Make sure we can commit to Intuit github"
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Release
          command: yarn release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/

      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
